package com.example.jobmatching.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

/**
 * Represents a candidate extracted from a CV PDF and confirmed by the user.
 *
 * <p>This POJO is used in two distinct phases:
 * <ol>
 *   <li><b>Review payload</b> — returned by {@code POST /candidates/parse-pdf}
 *       before anything is written to MongoDB. The {@code id}, {@code embedText},
 *       {@code embedding}, {@code createdAt}, and {@code updatedAt} fields are
 *       all {@code null} at this stage.</li>
 *   <li><b>Persisted document</b> — posted by the frontend via
 *       {@code POST /candidates} after the user confirms the review form. At
 *       this point the backend constructs {@code embedText}, calls the Atlas
 *       VoyageAI REST API to generate the {@code embedding}, and writes the
 *       full document to MongoDB.</li>
 * </ol>
 *
 * <h3>Embedding strategy</h3>
 * <p>Only the semantically meaningful fields are embedded:
 * <ul>
 *   <li>{@code summary} — captures career domain, seniority, and intent</li>
 *   <li>{@code skills} — name, area, and years for each skill</li>
 * </ul>
 * Identity fields ({@code name}, {@code email}, {@code phone}, {@code location}),
 * education, certification titles, and employment dates are stored in MongoDB
 * for filtering and display but are <em>not</em> included in {@code embedText}.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CandidateProfile {

    // ── Identity (stored, not embedded) ───────────────────────────────────

    /** MongoDB ObjectId as a hex string; null before insertion. */
    private String id;

    private String name;
    private String email;
    private String phone;
    private String location;

    // ── Semantic fields (embedded) ─────────────────────────────────────────

    /** Free-text career summary extracted from the CV "About" or "Summary" section. */
    private String summary;

    /**
     * Structured skills extracted from the CV.
     * Each entry carries a name, area, and estimated years of experience.
     */
    private List<Skill> skills;

    // ── Structured fields (stored, not embedded) ───────────────────────────

    private List<Experience> experience;
    private List<Education> education;
    private List<String> certifications;

    // ── Vector fields (populated at write time) ────────────────────────────

    /**
     * The normalised string that was sent to the Atlas VoyageAI REST API.
     * Storing it alongside the embedding makes the vector auditable and allows
     * re-embedding without re-running LLM extraction.
     *
     * <p>Format:
     * <pre>
     *   "{seniority} | Skills: {skill} ({area}, {years}yr), ... | Summary: {summary}"
     * </pre>
     */
    private String embedText;

    /**
     * The 1 024-element float vector generated by {@code voyage-4-large}.
     * Stored as a BSON double array and indexed by the Atlas Vector Search index.
     */
    private List<Double> embedding;

    // ── Metadata ───────────────────────────────────────────────────────────

    /** "pdf" or "manual". */
    private String source;

    /** "active" or "inactive". */
    private String status;

    private String createdAt;
    private String updatedAt;

    // ── Nested types ───────────────────────────────────────────────────────

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class Experience {
        private String company;
        private String title;
        private String start;
        private String end;
        private String description;

        public Experience() {}

        public String getCompany() { return company; }
        public void setCompany(String company) { this.company = company; }

        public String getTitle() { return title; }
        public void setTitle(String title) { this.title = title; }

        public String getStart() { return start; }
        public void setStart(String start) { this.start = start; }

        public String getEnd() { return end; }
        public void setEnd(String end) { this.end = end; }

        public String getDescription() { return description; }
        public void setDescription(String description) { this.description = description; }
    }

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class Education {
        private String degree;
        private String institution;
        private Integer year;

        public Education() {}

        public String getDegree() { return degree; }
        public void setDegree(String degree) { this.degree = degree; }

        public String getInstitution() { return institution; }
        public void setInstitution(String institution) { this.institution = institution; }

        public Integer getYear() { return year; }
        public void setYear(Integer year) { this.year = year; }
    }

    // ── Constructors ───────────────────────────────────────────────────────

    public CandidateProfile() {}

    // ── Getters & setters ──────────────────────────────────────────────────

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    public String getSummary() { return summary; }
    public void setSummary(String summary) { this.summary = summary; }

    public List<Skill> getSkills() { return skills; }
    public void setSkills(List<Skill> skills) { this.skills = skills; }

    public List<Experience> getExperience() { return experience; }
    public void setExperience(List<Experience> experience) { this.experience = experience; }

    public List<Education> getEducation() { return education; }
    public void setEducation(List<Education> education) { this.education = education; }

    public List<String> getCertifications() { return certifications; }
    public void setCertifications(List<String> certifications) { this.certifications = certifications; }

    public String getEmbedText() { return embedText; }
    public void setEmbedText(String embedText) { this.embedText = embedText; }

    public List<Double> getEmbedding() { return embedding; }
    public void setEmbedding(List<Double> embedding) { this.embedding = embedding; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }

    public String getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(String updatedAt) { this.updatedAt = updatedAt; }
}
