package com.example.jobmatching.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

/**
 * Represents a job posting extracted from a PDF and confirmed by the recruiter.
 *
 * <p>Lifecycle mirrors {@link CandidateProfile}: the object is first returned as
 * a review payload from {@code POST /jobs/parse-pdf} (nothing written to MongoDB),
 * and then persisted when the recruiter confirms via {@code POST /jobs}.
 *
 * <h3>Embedding strategy</h3>
 * <p>Only semantically meaningful content is included in {@code embedText}:
 * <ul>
 *   <li>{@code title} — sets domain and seniority context</li>
 *   <li>{@code requiredSkills} — name, area, minimum years</li>
 *   <li>{@code summary} — free-text role description</li>
 *   <li>{@code responsibilities} — duty bullets joined with {@code ". "}</li>
 * </ul>
 * Company name, location, salary, employment type, seniority enum (used as a
 * pre-filter instead), and preferred skills (scored structurally) are stored
 * but <em>not</em> embedded.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class JobPosting {

    // ── Identity (stored, not embedded) ───────────────────────────────────

    /** MongoDB ObjectId as a hex string; null before insertion. */
    private String id;

    private String company;
    private String location;

    /** "remote", "hybrid", or "on-site". */
    private String remotePolicy;

    /** "junior", "mid", "senior", "lead", or "principal". */
    private String seniority;

    /** "full-time", "part-time", or "contract". */
    private String employmentType;

    private Salary salary;

    // ── Semantic fields (embedded) ─────────────────────────────────────────

    /** The exact job title string, e.g. "Senior Data Engineer". */
    private String title;

    /** Free-text role description from the "About the Role" or "Summary" section. */
    private String summary;

    /** Duty bullet points from the "Responsibilities" section. */
    private List<String> responsibilities;

    /**
     * Required skills with minimum experience thresholds.
     * These are included in {@code embedText} and are the primary matching signal.
     */
    private List<RequiredSkill> requiredSkills;

    /**
     * Nice-to-have skills.
     * <em>Not</em> included in {@code embedText} — their weight comes from the
     * structured {@code skillOverlapScore} component in the composite score.
     */
    private List<RequiredSkill> preferredSkills;

    // ── Vector fields (populated at write time) ────────────────────────────

    /**
     * The normalised string that was sent to the Atlas VoyageAI REST API.
     *
     * <p>Format:
     * <pre>
     *   "{title} | Required: {skill} ({area}, {minYears}yr+), ... | Summary: {summary}
     *    | Responsibilities: {joined bullets}"
     * </pre>
     */
    private String embedText;

    /**
     * The 1 024-element float vector generated by {@code voyage-4-large}.
     */
    private List<Double> embedding;

    // ── Metadata ───────────────────────────────────────────────────────────

    /** "pdf" or "manual". */
    private String source;

    /** "draft" after extraction/review, "published" after recruiter confirmation. */
    private String status;

    private String createdAt;
    private String updatedAt;

    // ── Nested types ───────────────────────────────────────────────────────

    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class Salary {
        private Integer min;
        private Integer max;
        private String currency;

        public Salary() {}

        public Integer getMin() { return min; }
        public void setMin(Integer min) { this.min = min; }

        public Integer getMax() { return max; }
        public void setMax(Integer max) { this.max = max; }

        public String getCurrency() { return currency; }
        public void setCurrency(String currency) { this.currency = currency; }
    }

    // ── Constructors ───────────────────────────────────────────────────────

    public JobPosting() {}

    // ── Getters & setters ──────────────────────────────────────────────────

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getCompany() { return company; }
    public void setCompany(String company) { this.company = company; }

    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    public String getRemotePolicy() { return remotePolicy; }
    public void setRemotePolicy(String remotePolicy) { this.remotePolicy = remotePolicy; }

    public String getSeniority() { return seniority; }
    public void setSeniority(String seniority) { this.seniority = seniority; }

    public String getEmploymentType() { return employmentType; }
    public void setEmploymentType(String employmentType) { this.employmentType = employmentType; }

    public Salary getSalary() { return salary; }
    public void setSalary(Salary salary) { this.salary = salary; }

    public String getSummary() { return summary; }
    public void setSummary(String summary) { this.summary = summary; }

    public List<String> getResponsibilities() { return responsibilities; }
    public void setResponsibilities(List<String> responsibilities) { this.responsibilities = responsibilities; }

    public List<RequiredSkill> getRequiredSkills() { return requiredSkills; }
    public void setRequiredSkills(List<RequiredSkill> requiredSkills) { this.requiredSkills = requiredSkills; }

    public List<RequiredSkill> getPreferredSkills() { return preferredSkills; }
    public void setPreferredSkills(List<RequiredSkill> preferredSkills) { this.preferredSkills = preferredSkills; }

    public String getEmbedText() { return embedText; }
    public void setEmbedText(String embedText) { this.embedText = embedText; }

    public List<Double> getEmbedding() { return embedding; }
    public void setEmbedding(List<Double> embedding) { this.embedding = embedding; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }

    public String getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(String updatedAt) { this.updatedAt = updatedAt; }
}
